### ISSUE TITLE
"Dark Mode" support

### ISSUE THREAD

**Issue by cara-tm** [Bloke/rss_admin_db_manager#1]
For better a new "Dark Mode" support, may be you could change the inline background color style by this one instead (https://github.com/Bloke/rss_admin_db_manager/blob/master/rss_admin_db_manager.php#L376):

`background-color: inherit`

**Comment by Bloke** [comment]
How about this instead? 6f482857

**Comment by cara-tm** [comment]
Just perfect! 👌
